name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.5.0'

    - name: Install dependencies
      run: npm install

    - name: Build and Deploy
      run: |
        npm run deploy
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

